### ISSUE TITLE
FTRE – 3 - Disponiblização de API backend

### ISSUE THREAD

**Issue by marcus-vinf** [vinicius-escano/plataforma-conscientiza-backend#15]
Feature para construir a API backend que tratará os dados.

O backend do serviço é o responsável por praticamente toda a lógica com o qual tratamos os dados.
Para a construção de um bom backend deve ser levado em consideração a eficiencia e segurança no tratamento de dados.

O serviço se baseará já plataforma Java + Spring, que conta com recursos que tornam a construção mais rápida.

Essa feature disponibilizará a API para criação e manutenção dos registros de dados

--------------------------------------------
UML

entidade: registro
**Id**: uuid;
**navegador**: string;
**horarioAcesso**: date;
**tipoAparelho**: string.
**origemAcesso**: enumOrigemAcesso

**enum**: enumOrigemAcesso
Values:
DESKTOP_MESSAGE
DESKTOP_EMAIL
MOBILE_MESSAGE
MOBILE_QRCODE

- A entidade deve ser de registro único para cada acesso a plataforma, validar o Id como chave primária.
- Para gerenciar essa entidade devem ser disponibilizados os construtores e acessos por meio de get/set seguindo as boas práticas de desenvolvimento.

- [x] #24
- [x] Criar scripts SQL para inserção em banco de dados, e fazer com que seja executado ao iniciar o serviço (migração automática)
- [x] #23
- [x] Disponibilizar os endpoints para acesso ao CRUD da entidade

------------------------------------- 

- Validar a estrutura e funcionalidade da entidade criada. Criar testes unitários para validar o funcionamento do CRUD

**Validar**:
- [x] Criação
- [x] Edição
- [x] List/Gets
- [x] Delete
- [x] Constraints 

Critérios de aceite:
1 – Estrutura definida seguindo as boas práticas de desenvolvimento.
2 – Endpoints responsivos.
3 – Integridade de dados. Não permitir duplicidade

**Comment by vinicius-escano** [comment]
teste

**Comment by vinicius-escano** [comment]
Ajustado descrição da tarefa

**Comment by vinicius-escano** [comment]
Commit da tarefa

[FTRE-3](https://github.com/vinicius-escano/plataforma-conscientiza-backend/commit/adcf052d93fc0d7e169dcc23722008e09ea992e7)

**Comment by vinicius-escano** [comment]
Utilização do CRUD

URL: http://localhost:8081/api/registries

CREATE
![Image](https://github.com/user-attachments/assets/164d73c2-e121-4e27-b6a8-b99c925b273f)

READ
ListAll
![Image](https://github.com/user-attachments/assets/fa69002b-51c7-4382-921f-fa4e17414c71)

FindById
![Image](https://github.com/user-attachments/assets/2ae3384e-c1db-4d75-a640-6a77eea6f773)

UPDATE
![Image](https://github.com/user-attachments/assets/9e8cd141-dae0-4ff1-8d5a-c75e0f29de63)

DELETE
![Image](https://github.com/user-attachments/assets/05944862-da7f-4b20-8dee-b3db28014dda)

**Comment by davifma** [comment]
Onde está o UML? Quais são os diagramas?

Qual o endereço da API? Temos um Swegger dela?

**Comment by vinicius-escano** [comment]
UML:
![Image](https://github.com/user-attachments/assets/e157f68a-8de7-4482-a158-2b1bf7882214)


A API está rodando localmente ainda, e o swagger não se faz necessário pois todos os acessos até o momento estão listados no CRUD comentado acima

**Comment by davifma** [comment]
UML com Primary Key? Que diagrama é esse?
